# Generated by Django 2.2.3 on 2019-08-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190813_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='customer',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Order'),
            preserve_default=False,
        ),
    ]
