# Generated by Django 2.2.3 on 2019-08-13 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BagType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('frame', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('NTN', models.CharField(max_length=50)),
                ('GST', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoomStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('bag_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.BagType')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('bag_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.BagType')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='PrintingStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.FloatField()),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RpmReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_no', models.IntegerField()),
                ('mac_address', models.CharField(max_length=17)),
                ('rpm', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stereo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('NTN', models.CharField(max_length=50)),
                ('GST', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TapeStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tape_type_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TapeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denier', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Quality')),
            ],
        ),
        migrations.CreateModel(
            name='Tapeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Inventory')),
                ('tape_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TapeType')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('unit', models.DecimalField(decimal_places=1, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=12)),
                ('price', models.IntegerField()),
                ('comments', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Printing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('loom_stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.LoomStock')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Order')),
                ('stereo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Stereo')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='stereo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Stereo'),
        ),
        migrations.CreateModel(
            name='Loom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loom_number', models.IntegerField()),
                ('circumference', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity', models.FloatField()),
                ('bag_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.BagType')),
                ('tape_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TapeType')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.ItemCategory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Item'),
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dispatch_time', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Customer')),
                ('printing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Printing')),
            ],
        ),
        migrations.AddField(
            model_name='bagtype',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Quality'),
        ),
    ]
