# Generated by Django 2.2.3 on 2019-08-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190826_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='comments',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='GST',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='NTN',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='comments',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='GST',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='NTN',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
