# Generated by Django 2.2.3 on 2019-10-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190829_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpmreading',
            name='mac_address',
        ),
    ]
