# Generated by Django 2.2.3 on 2019-10-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_rpmreading_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpmreading',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
