# Generated by Django 2.2.3 on 2019-10-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191029_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpmreading',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
