# Generated by Django 2.2.3 on 2019-11-14 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191115_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpmreading',
            name='loom_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Loom'),
            preserve_default=False,
        ),
    ]
