# Generated by Django 2.2.3 on 2019-11-14 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rpmreading_loom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpmreading',
            name='loom_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Loom'),
        ),
    ]
