# Generated by Django 2.2.3 on 2019-11-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191114_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpmreading',
            old_name='loom_id',
            new_name='loom',
        ),
    ]
