# Generated by Django 2.2.3 on 2019-11-14 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191114_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpmreading',
            name='loom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Loom'),
            preserve_default=False,
        ),
    ]
