# Generated by Django 2.2.3 on 2019-11-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20191114_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpmreading',
            name='loom',
            field=models.CharField(max_length=100),
        ),
    ]
