# Generated by Django 2.2.3 on 2019-12-12 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20191114_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpmreading',
            name='loom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Loom'),
        ),
    ]
